import AppKit
import Combine

/// Observa o clipboard (quando habilitado nas configurações) e
/// transforma capturas em itens da linha do tempo: arquivos entram por
/// referência; texto e imagens são salvos no cofre do app.
@MainActor
final class ClipboardMonitor: ObservableObject {
    @Published private(set) var items: [FileItem] = []

    private var timer: Timer?
    private var lastChange = NSPasteboard.general.changeCount

    private struct StoredItem: Codable {
        let path: String
        let name: String
        let date: Date
    }

    private var storeURL: URL {
        Prefs.supportDirectory("Clipboard").appendingPathComponent("itens.json")
    }

    func start() {
        guard timer == nil else { return }
        load()
        pruneExpired()
        let timer = Timer(timeInterval: 1.0, repeats: true) { [weak self] _ in
            Task { @MainActor in self?.tick() }
        }
        timer.tolerance = 0.3
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    private func tick() {
        guard Prefs.clipboardTimelineEnabled else { return }
        let pasteboard = NSPasteboard.general
        guard pasteboard.changeCount != lastChange else { return }
        lastChange = pasteboard.changeCount
        pruneExpired()

        // Privacidade: respeita as marcações padrão do pasteboard.
        // Gerenciadores de senhas (1Password, Bitwarden…) marcam o que
        // copiam como "concealed"; apps marcam conteúdo descartável
        // como "transient"/"auto-generated".
        let types = pasteboard.types ?? []
        if Prefs.clipboardSkipConcealed,
           types.contains(NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")) {
            return
        }
        if Prefs.clipboardSkipTransient,
           types.contains(NSPasteboard.PasteboardType("org.nspasteboard.TransientType"))
            || types.contains(NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")) {
            return
        }

        if let urls = pasteboard.readObjects(forClasses: [NSURL.self]) as? [URL],
           !urls.isEmpty, urls.allSatisfy(\.isFileURL) {
            add(urls.map { FileItem(url: $0) })
            return
        }

        if let image = NSImage(pasteboard: pasteboard),
           let tiff = image.tiffRepresentation,
           let rep = NSBitmapImageRep(data: tiff),
           let png = rep.representation(using: .png, properties: [:]) {
            let url = destination(name: "Clipboard \(stamp())", ext: "png")
            if (try? png.write(to: url)) != nil {
                add([FileItem(url: url)])
            }
            return
        }

        if let text = pasteboard.string(forType: .string) {
            let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
            guard trimmed.count > 2 else { return }

            // Link copiado vira .webloc com o host no nome (e arte de
            // link no preview); texto comum vira .txt nomeado pelo
            // próprio conteúdo.
            if let link = URL(string: trimmed),
               link.scheme?.hasPrefix("http") == true, link.host != nil {
                let plist: [String: Any] = ["URL": trimmed]
                if let data = try? PropertyListSerialization.data(
                    fromPropertyList: plist, format: .xml, options: 0
                ) {
                    let name = "Link — \(sanitize(link.host ?? "web"))"
                    let url = destination(name: name, ext: "webloc")
                    if (try? data.write(to: url)) != nil {
                        add([cleanNamedItem(url: url, name: name)])
                    }
                }
            } else {
                // Textos com cara de senha/chave nunca tocam o disco.
                if Prefs.clipboardSkipSecretLike, SecretSniffer.looksLikeSecret(trimmed) {
                    return
                }
                // Item de TEXTO: nome é o próprio conteúdo (sem ".txt"
                // aparente — arrastar cola como texto).
                let preview = sanitize(String(trimmed.prefix(28)))
                let name = preview.isEmpty ? "Texto \(stamp())" : preview
                let url = destination(name: name, ext: "txt")
                if (try? text.write(to: url, atomically: true, encoding: .utf8)) != nil {
                    add([cleanNamedItem(url: url, name: name)])
                }
            }
        }
    }

    /// Item com nome limpo (sem extensão visível).
    private func cleanNamedItem(url: URL, name: String) -> FileItem {
        FileItem(
            url: url,
            name: name,
            isDirectory: false,
            date: Date(),
            size: Int64((try? url.resourceValues(forKeys: [.fileSizeKey]).fileSize) ?? 0)
        )
    }

    private func sanitize(_ name: String) -> String {
        name
            .replacingOccurrences(of: "/", with: " ")
            .replacingOccurrences(of: ":", with: " ")
            .replacingOccurrences(of: "\n", with: " ")
            .trimmingCharacters(in: .whitespacesAndNewlines)
    }

    /// Remove itens da lista (chamado quando docs do clipboard são
    /// apagados/movidos ao Lixo — paridade com os docs da pasta).
    func remove(_ urls: [URL]) {
        let removed = Set(urls)
        let before = items.count
        items.removeAll { removed.contains($0.url) }
        if items.count != before { save() }
    }

    /// Expurga entradas cujos arquivos sumiram (apagados por fora).
    func pruneMissing() {
        pruneExpired()
        let before = items.count
        items.removeAll { !FileManager.default.fileExists(atPath: $0.url.path) }
        if items.count != before { save() }
    }

    /// Expiração automática (Configurações → Segurança): itens antigos
    /// saem da lista e as cópias guardadas no cofre são apagadas de
    /// vez. Arquivos referenciados de fora ficam intactos no disco.
    func pruneExpired() {
        let hours = Prefs.clipboardRetentionHours
        guard hours > 0 else { return }
        let cutoff = Date().addingTimeInterval(-hours * 3600)
        let expired = items.filter { $0.date < cutoff }
        guard !expired.isEmpty else { return }
        let vault = Prefs.supportDirectory("Clipboard").path
        for item in expired where item.url.path.hasPrefix(vault) {
            try? FileManager.default.removeItem(at: item.url)
        }
        items.removeAll { $0.date < cutoff }
        save()
    }

    /// Limpa todo o histórico agora (botão em Segurança). Cópias do
    /// cofre são apagadas de vez; arquivos de fora só saem da lista.
    func clearAll() {
        let vault = Prefs.supportDirectory("Clipboard").path
        for item in items where item.url.path.hasPrefix(vault) {
            try? FileManager.default.removeItem(at: item.url)
        }
        items = []
        save()
    }

    private func add(_ newItems: [FileItem]) {
        var merged = newItems + items.filter { existing in
            !newItems.contains(where: { $0.url == existing.url })
        }
        if merged.count > 50 {
            merged = Array(merged.prefix(50))
        }
        items = merged
        save()
    }

    /// Persistência: o histórico do clipboard sobrevive a reaberturas.
    private func load() {
        guard let data = try? Data(contentsOf: storeURL),
              let stored = try? JSONDecoder().decode([StoredItem].self, from: data)
        else { return }
        items = stored.compactMap { entry in
            let url = URL(fileURLWithPath: entry.path)
            guard FileManager.default.fileExists(atPath: url.path) else { return nil }
            return FileItem(
                url: url,
                name: entry.name,
                isDirectory: false,
                date: entry.date,
                size: Int64((try? url.resourceValues(forKeys: [.fileSizeKey]).fileSize) ?? 0)
            )
        }
    }

    private func save() {
        let stored = items.map {
            StoredItem(path: $0.url.path, name: $0.name, date: $0.date)
        }
        guard let data = try? JSONEncoder().encode(stored) else { return }
        try? data.write(to: storeURL, options: .atomic)
    }

    private func stamp() -> String {
        let formatter = DateFormatter()
        formatter.dateFormat = "yyyy-MM-dd HH.mm.ss"
        return formatter.string(from: Date())
    }

    private func destination(name: String, ext: String) -> URL {
        let dir = Prefs.supportDirectory("Clipboard")
        let plain = dir.appendingPathComponent("\(name).\(ext)")
        guard FileManager.default.fileExists(atPath: plain.path) else { return plain }
        return dir.appendingPathComponent("\(name) \(stamp()).\(ext)")
    }
}
